name: Setup Node
description: Node.js setup steps for GitHub Actions

runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        package_json_file: package.json
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        always-auth: false
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml
        node-version-file: package.json
