name: Typo / Grammar Fix
description: Report a typo / grammar issue
labels: [ pending triage ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a typo / grammar issue!

        If the typo / grammar issue is trivial and straightforward, you can help by **creating a quick pull request**!
        If you spot multiple issues, please combine them into a single PR.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the typo / grammar issue.
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: 'Before submitting the issue, I attest that I have read and agree to the following:'
      options:
        - label: 'The [Code of Conduct](https://github.com/infernodesign/codegasm-theme/blob/main/CODE_OF_CONDUCT.md)'
          required: true
        - label: 'The [Contributing Guide](https://github.com/infernodesign/codegasm-theme/blob/main/CONTRIBUTING.md)'
          required: true
        - label: I have checked for existing issues that report the same typo / grammar issue.
          required: true
  - type: checkboxes
    id: contributions
    attributes:
      label: Contributions
      description: This project is maintained by volunteers, so your help is greatly appreciated.
      options:
        - label: I am willing to submit a PR to fix this issue
